---
title: "discussion_3_key"
format: docx
---

# Question 1
```{r}
#| include: false
library(tidyverse)

w_bar <- function(p, w11, w12, w22){
  q <- 1-p
  
  p^2*w11 + 2*p*q*w12 + q^2*w22
}

p_prime <- function(p, w11, w12, w22){
  q <- 1-p
  (p/w_bar(p, w11, w12, w22))*(p*w11 + q*w12)
}
```

```{r}
#| echo: false

d <- read.csv("q1.csv")
d %>% 
  group_by(genotype) %>% 
  summarise(prop.survive = mean(survive)) %>% 
  mutate(rel.fit = prop.survive/max(prop.survive))
  
```

Equilibrium points 0,1 and `r round((1 - .625)/(.75 + 1 - 2*.625), 3)`.

```{r}
#| echo: false
phat <- (1 - .625)/(.75 + 1 - 2*.625)
curve(w_bar(x, .75, .625, 1), xlab = "p", ylab = "Mean Fitness", lwd = 2)
points(c(1, w_bar(phat, .75, .625, 1), .75) ~ c(0, phat, 1), pch = 20, cex = 2)
```
# Question 2

```{r}
#| echo: false
d <- read.csv("q2.csv")
d %>% 
  group_by(genotype) %>% 
  summarise(prop.survive = mean(survive)) %>% 
  mutate(rel.fit = prop.survive/max(prop.survive))
```

$\hat{q} = \sqrt{\frac{\mu}{s}}$. s = 0.375. $\hat{q} = 0.016$


# Question 3

```{r}
#| echo: false
d <- read.csv("q3.csv")
d %>% 
  group_by(population) %>% 
  summarise(p = sum(genotype)/(2*n()))
```

$p_t = \frac{.287 + .587}{2} = .437$  

$H_t = 2(.437)(.563) = .492$

$H_s = \frac{2(.287)(.713) + 2(.587)(.413)}{2} = .447$

$F_{ST} = \frac{.492 - .447}{.492} = 0.091$

# Question 4

4.1: $H_{g+t} = .5(1-\frac{1}{2000})^{10} = .498$

4.2: $N_e = \frac{4(250)(500)}{250 + 500} = 666.67$; $H_{g+t} = .5(1-\frac{1}{2(666.67)})^{10} = .496$

# Question 5

5.1:

```{r}
.5*(1-1/40)^(c(5,10,15))
```
```{r}
#| echo: false
h <- c(.5,.5*(1-1/40)^(c(5,10,15)))
gen <- c(0,5,10,15)
plot(h ~ gen, pch = 20, cex = 2)
```
5.2:

You can either solve for Ne, or plug in numbers and get it through trial and error.

~11-11.5

# Question 6

```{r}
#| echo: false
d <- read.csv("q6.csv")

d %>% 
  group_by(genotype) %>% 
  summarise(prop.survive = mean(survive)) %>% 
  mutate(rel.fit = prop.survive/max(prop.survive))
```

Make p the frequency of the A2 allele:

```{r}
(1-.03)*.8 + .03*0
```
Fitness before:

```{r}
.8^2*1 + 2*.8*.2*.889 + .2^2*.667
```
Fitness after:

```{r}
.776^2*1 + 2*.776*.224*.889 + .224^2*.667
```

